package progassmentcom.quickchat;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
 * JUnit tests for Message class.
 * Tests the refactored Message implementation with auto-generated IDs.
 */
public class MessageTest {

    @Test
    public void testMessageLengthOK() {
        Message msg = new Message("+27718693002", "Hi Mike, can you join us for dinner tonight?");
        assertEquals("Message ready to send.", msg.checkMessageLength());
    }

    @Test
    public void testMessageLengthExceeded() {
        String longMessage = "A".repeat(260);
        Message msg = new Message("+27718693002", longMessage);
        assertEquals("Message exceeds 250 characters by 10; please reduce the size.", msg.checkMessageLength());
    }

    @Test
    public void testRecipientCorrectlyFormatted() {
        Message msg = new Message("+27718693002", "Hi Mike");
        assertEquals("Cell phone number successfully captured.", msg.checkRecipientCell());
    }

    @Test
    public void testRecipientIncorrectlyFormatted() {
        Message msg = new Message("08575975889", "Hi Keegan");
        assertEquals("Cell phone number is incorrectly formatted or does not contain an international code. "
                   + "Please correct the number and try again.", msg.checkRecipientCell());
    }

    @Test
    public void testMessageHashCorrect() {
        Message msg = new Message("+27718693002", "Hi Mike, can you join us for dinner tonight?");
        msg.setMessageNumber(0);
        String hash = msg.createMessageHash();
        
        // Hash should be in format: first2digits:messageNumber:firstWordLastWord
        // The first 2 digits depend on the generated ID
        assertTrue(hash.contains(":0:"));
        assertTrue(hash.contains("HI"));
        assertTrue(hash.contains("TONIGHT"));
    }

    @Test
    public void testMessageHashWithSpecificID() {
        Message msg = new Message("+27718693002", "Hi Mike, can you join us for dinner tonight?");
        msg.messageID = "0012345678";  // Set specific ID for testing
        msg.setMessageNumber(0);
        String hash = msg.createMessageHash();
        
        // With ID "0012345678", first 2 digits = "00"
        assertEquals("00:0:HITONIGHT", hash);
    }

    @Test
    public void testMessageIDGenerated() {
        Message msg = new Message("+27718693002", "Test message");
        
        assertNotNull(msg.getMessageID());
        assertEquals(10, msg.getMessageID().length());
        assertTrue(msg.checkMessageID());
    }

    @Test
    public void testMessageIDAutoGeneratedDifferent() {
        Message msg1 = new Message("+27718693002", "Message 1");
        Message msg2 = new Message("+27718693002", "Message 2");
        
        // IDs should be different (very high probability with random generation)
        assertNotEquals(msg1.getMessageID(), msg2.getMessageID());
    }

    @Test
    public void testCheckMessageIDValid() {
        Message msg = new Message("+27718693002", "Test");
        // Auto-generated ID should be valid
        assertTrue(msg.checkMessageID());
    }

    @Test
    public void testCheckMessageIDInvalid() {
        Message msg = new Message("+27718693002", "Test");
        msg.messageID = "12345678901";  // 11 digits - invalid
        assertFalse(msg.checkMessageID());
    }

    @Test
    public void testMessageSentStatusSend() {
        Message msg = new Message("+27718693002", "Hi Mike, can you join us for dinner tonight?");
        String result = msg.sentMessage(1);
        
        assertEquals("Message successfully sent.", result);
        assertTrue(msg.isMessageSent());
    }

    @Test
    public void testMessageSentStatusDisregard() {
        Message msg = new Message("+27718693002", "Hi Keegan, did you receive the payment?");
        String result = msg.sentMessage(2);
        
        assertEquals("Press 0 to delete the message.", result);
        assertFalse(msg.isMessageSent());
    }

    @Test
    public void testMessageSentStatusStore() {
        Message msg = new Message("+27718693002", "Test message");
        String result = msg.sentMessage(3);
        
        assertEquals("Message successfully stored.", result);
        assertFalse(msg.isMessageSent());
    }

    @Test
    public void testMessageSentStatusInvalid() {
        Message msg = new Message("+27718693002", "Test message");
        String result = msg.sentMessage(99);
        
        assertEquals("Invalid choice.", result);
        assertFalse(msg.isMessageSent());
    }

    @Test
    public void testGettersWork() {
        Message msg = new Message("+27718693002", "Test content");
        msg.setMessageNumber(5);
        
        assertEquals("+27718693002", msg.getRecipient());
        assertEquals("Test content", msg.getMessageContent());
        assertEquals(5, msg.getMessageNumber());
        assertNotNull(msg.getMessageID());
        assertFalse(msg.isMessageSent());
    }

    @Test
    public void testMessageHashNullContent() {
        Message msg = new Message("+27718693002", "");
        msg.messageID = "0012345678";
        String hash = msg.createMessageHash();
        
        // Empty message should default to "MESSAGE"
        assertEquals("00:0:MESSAGEMESSAGE", hash);
    }

    @Test
    public void testMessageWithSingleWordContent() {
        Message msg = new Message("+27718693002", "Hello");
        msg.messageID = "1234567890";
        msg.setMessageNumber(2);
        String hash = msg.createMessageHash();
        
        // Single word means first and last word are the same
        assertEquals("12:2:HELLOHELLO", hash);
    }

    @Test
    public void testMessageIDLength() {
        for (int i = 0; i < 10; i++) {
            Message msg = new Message("+27718693002", "Test");
            // Every generated ID should be exactly 10 characters
            assertEquals(10, msg.getMessageID().length());
            // Should be numeric
            assertTrue(msg.getMessageID().matches("\\d{10}"));
        }
    }

    @Test
    public void testRecipientWithInvalidFormat() {
        Message msg = new Message("12345", "Test");
        assertEquals("Cell phone number is incorrectly formatted or does not contain an international code. "
                   + "Please correct the number and try again.", msg.checkRecipientCell());
    }

    @Test
    public void testRecipientWithTooLongNumber() {
        Message msg = new Message("+27718693002123456", "Test");  // Longer than 13
        assertEquals("Cell phone number is incorrectly formatted or does not contain an international code. "
                   + "Please correct the number and try again.", msg.checkRecipientCell());
    }

    @Test
    public void testMessageLengthBoundary250() {
        String exactly250 = "A".repeat(250);
        Message msg = new Message("+27718693002", exactly250);
        assertEquals("Message ready to send.", msg.checkMessageLength());
    }

    @Test
    public void testMessageLengthBoundary251() {
        String exactly251 = "A".repeat(251);
        Message msg = new Message("+27718693002", exactly251);
        assertEquals("Message exceeds 250 characters by 1; please reduce the size.", msg.checkMessageLength());
    }
}